#!/bin/sh
rm *.o
/mnt/dgf1/home/sachinp/workspace/CN2/cn < /mnt/dgf1/home/sachinp/workspace/HindiLinguisticResources/Learned/Resources/TrainingInstances/c
RULEFILENAME="rules.ord.$1"
./formatRules.DINESH.pl o ./ > $RULEFILENAME
rm -f rules.ord
ln -s $RULEFILENAME rules.ord
